// GENERATED by npm run genmaps from content/maps/cinderwaste.map.txt - DO NOT EDIT
import type { CompiledMap } from '../../core/mapdefs.ts';

export const cinderwaste = {
  "id": "cinderwaste",
  "width": 30,
  "height": 20,
  "music": "ashenreach",
  "tiles": [
    "ooo-oooooooooooooooooooooooooo",
    "o............................o",
    "o............................o",
    "o............................o",
    "o............................o",
    "o............................o",
    "o...........,,,,,,,,,,,,,,...o",
    "o...........,,,,,,,,,,,,,,...o",
    "o...........,,,,,,,,,,,,,,...o",
    "o...........,,,,,,,,,,,,,,...o",
    "o...........,,,,,,,,,,,,,,...o",
    "o............................o",
    "o............................o",
    "o..,,,,,,,,..................o",
    "o..,,,,,,,,..................o",
    "o..,,,,,,,,..................o",
    "o..,,,,,,,,..................o",
    "o..,,,,,,,,..................o",
    "o............................o",
    "oooooooooooooooooooooooooooooo"
  ],
  "spawn": {
    "x": 3,
    "y": 2,
    "facing": "down"
  },
  "zones": [
    {
      "name": "wastes",
      "rect": {
        "x1": 12,
        "y1": 6,
        "x2": 25,
        "y2": 10
      },
      "table": "cinderwaste.wastes"
    },
    {
      "name": "deep",
      "rect": {
        "x1": 3,
        "y1": 13,
        "x2": 10,
        "y2": 17
      },
      "table": "cinderwaste.deep"
    }
  ],
  "exits": [
    {
      "x": 3,
      "y": 0,
      "to": "wayhold",
      "tx": 1,
      "ty": 6
    }
  ],
  "npcs": [
    {
      "id": "armorer",
      "x": 5,
      "y": 3,
      "dialogue": "armorer_base"
    }
  ],
  "signs": [
    {
      "x": 6,
      "y": 2,
      "dialogue": "cinderwaste_sign"
    }
  ],
  "lore": [
    {
      "x": 26,
      "y": 3,
      "dialogue": "lore_cinder"
    }
  ],
  "springs": [],
  "shrines": [],
  "egates": [],
  "bosses": [
    {
      "id": "emberjaw",
      "x": 24,
      "y": 11
    },
    {
      "id": "pyrewarden",
      "x": 24,
      "y": 18
    }
  ],
  "gates": [],
  "triggers": [],
  "trials": [],
  "theme": "ember",
  "portals": [
    {
      "dungeon": "emberforge",
      "x": 14,
      "y": 12,
      "to": "emberforge",
      "tx": 12,
      "ty": 11
    }
  ],
  "levers": [],
  "doors": [],
  "chests": [],
  "objectives": [],
  "minibosses": [],
  "waystones": [
    {
      "id": "cinder_stone",
      "x": 3,
      "y": 4
    }
  ],
  "plates": [],
  "ambushes": []
} as const satisfies CompiledMap;
