// GENERATED by npm run genmaps from content/maps/circuitvault.map.txt - DO NOT EDIT
import type { CompiledMap } from '../../core/mapdefs.ts';

export const circuitvault = {
  "id": "circuitvault",
  "width": 17,
  "height": 13,
  "music": "ashenreach",
  "tiles": [
    "ooooooooooooooooo",
    "ooooooo---ooooooo",
    "ooooooo---ooooooo",
    "ooooooo---ooooooo",
    "oooooooo-oooooooo",
    "oooooooo-oooooooo",
    "oooooooo-oooooooo",
    "o---------------o",
    "o----,,,,,,-----o",
    "o---------------o",
    "o---------------o",
    "o---------------o",
    "ooooooooooooooooo"
  ],
  "spawn": {
    "x": 12,
    "y": 11,
    "facing": "up"
  },
  "zones": [
    {
      "name": "live",
      "rect": {
        "x1": 1,
        "y1": 7,
        "x2": 15,
        "y2": 9
      },
      "table": "circuitvault.live"
    }
  ],
  "exits": [],
  "npcs": [],
  "signs": [
    {
      "x": 2,
      "y": 7,
      "dialogue": "vault_note"
    }
  ],
  "lore": [
    {
      "x": 14,
      "y": 8,
      "dialogue": "lore_vault"
    }
  ],
  "springs": [],
  "shrines": [],
  "egates": [],
  "bosses": [],
  "gates": [],
  "triggers": [],
  "trials": [],
  "theme": "ash",
  "portals": [
    {
      "dungeon": "circuitvault",
      "x": 3,
      "y": 11,
      "to": "ashenreach",
      "tx": 5,
      "ty": 20
    }
  ],
  "levers": [],
  "doors": [
    {
      "id": "vault_gate",
      "x": 8,
      "y": 5,
      "needs": "plate:pressure_1"
    }
  ],
  "chests": [
    {
      "id": "vault_cache",
      "x": 12,
      "y": 9,
      "reward": "essence:25"
    }
  ],
  "objectives": [
    {
      "id": "vault_core",
      "x": 8,
      "y": 2,
      "battle": "circuit_core"
    }
  ],
  "minibosses": [],
  "waystones": [],
  "plates": [
    {
      "id": "pressure_1",
      "x": 7,
      "y": 9
    }
  ],
  "ambushes": [
    {
      "id": "vault_guard",
      "x": 8,
      "y": 6,
      "table": "circuitvault.live",
      "lv": 8,
      "repeat": false
    }
  ]
} as const satisfies CompiledMap;
