// GENERATED by npm run genmaps from content/maps/emberforge.map.txt - DO NOT EDIT
import type { CompiledMap } from '../../core/mapdefs.ts';

export const emberforge = {
  "id": "emberforge",
  "width": 17,
  "height": 13,
  "music": "ashenreach",
  "tiles": [
    "ooooooooooooooooo",
    "ooooooo---ooooooo",
    "ooooooo---ooooooo",
    "ooooooo---ooooooo",
    "oooooooo-oooooooo",
    "oooooooo-oooooooo",
    "oooooooo-oooooooo",
    "o---------------o",
    "o----,,,,,,-----o",
    "o---------------o",
    "o---------------o",
    "o---------------o",
    "ooooooooooooooooo"
  ],
  "spawn": {
    "x": 12,
    "y": 11,
    "facing": "up"
  },
  "zones": [
    {
      "name": "forge",
      "rect": {
        "x1": 1,
        "y1": 7,
        "x2": 15,
        "y2": 9
      },
      "table": "emberforge.forge"
    }
  ],
  "exits": [],
  "npcs": [],
  "signs": [
    {
      "x": 2,
      "y": 7,
      "dialogue": "emberforge_sign"
    }
  ],
  "lore": [
    {
      "x": 14,
      "y": 8,
      "dialogue": "lore_emberforge"
    }
  ],
  "springs": [],
  "shrines": [],
  "egates": [],
  "bosses": [],
  "gates": [],
  "triggers": [],
  "trials": [],
  "theme": "ember",
  "portals": [
    {
      "dungeon": "emberforge",
      "x": 3,
      "y": 11,
      "to": "cinderwaste",
      "tx": 14,
      "ty": 12
    }
  ],
  "levers": [
    {
      "id": "bellows",
      "x": 4,
      "y": 9
    }
  ],
  "doors": [
    {
      "id": "forge_gate",
      "x": 8,
      "y": 5,
      "needs": "lever:bellows"
    }
  ],
  "chests": [
    {
      "id": "forge_cache",
      "x": 12,
      "y": 9,
      "reward": "essence:20"
    }
  ],
  "objectives": [
    {
      "id": "forge_boss",
      "x": 8,
      "y": 2,
      "battle": "forge_heart"
    }
  ],
  "minibosses": [],
  "waystones": [],
  "plates": [],
  "ambushes": []
} as const satisfies CompiledMap;
