// GENERATED by npm run genmaps from content/maps/hearth.map.txt - DO NOT EDIT
import type { CompiledMap } from '../../core/mapdefs.ts';

export const hearth = {
  "id": "hearth",
  "width": 30,
  "height": 20,
  "music": "hearth",
  "tiles": [
    "###############.##############",
    "#..............-.............#",
    "#....*.........-....*........#",
    "#..#...........-.........#...#",
    "#..............-.............#",
    "#..............-.............#",
    "#..............-.............#",
    "#....*.........-....*........#",
    "#..............-.............#",
    "#..............-.............#",
    "-..------------------------..-",
    "#..............-.............#",
    "#..............-.............#",
    "#..........o...-...o.........#",
    "#..............-.............#",
    "#....*.........-....*........#",
    "#..............-.............#",
    "#..............-.............#",
    "#..............-.............#",
    "###############-##############"
  ],
  "spawn": {
    "x": 15,
    "y": 10,
    "facing": "down"
  },
  "zones": [],
  "exits": [
    {
      "x": 15,
      "y": 19,
      "to": "hearthvale",
      "tx": 30,
      "ty": 1
    },
    {
      "x": 0,
      "y": 10,
      "to": "westwood",
      "tx": 57,
      "ty": 20
    },
    {
      "x": 29,
      "y": 10,
      "to": "ashenreach",
      "tx": 2,
      "ty": 20
    },
    {
      "x": 15,
      "y": 0,
      "to": "northhollow",
      "tx": 24,
      "ty": 37
    }
  ],
  "npcs": [
    {
      "id": "elder",
      "x": 12,
      "y": 5,
      "dialogue": "elder_intro"
    },
    {
      "id": "keeper",
      "x": 19,
      "y": 6,
      "dialogue": "keeper_tips"
    },
    {
      "id": "dreamer",
      "x": 5,
      "y": 8,
      "dialogue": "dreamer_lore"
    },
    {
      "id": "twin_a",
      "x": 23,
      "y": 12,
      "dialogue": "twins_gossip_a"
    },
    {
      "id": "twin_b",
      "x": 24,
      "y": 12,
      "dialogue": "twins_gossip_b"
    },
    {
      "id": "scout",
      "x": 12,
      "y": 16,
      "dialogue": "scout_hints"
    },
    {
      "id": "armorer",
      "x": 8,
      "y": 5,
      "dialogue": "armorer_base"
    }
  ],
  "signs": [],
  "lore": [],
  "springs": [
    {
      "x": 21,
      "y": 6
    }
  ],
  "shrines": [],
  "egates": [
    {
      "id": "shed",
      "x": 4,
      "y": 16
    }
  ],
  "bosses": [],
  "gates": [
    {
      "id": "north",
      "x": 15,
      "y": 0
    }
  ],
  "triggers": [],
  "trials": [],
  "theme": "vale",
  "portals": [],
  "levers": [],
  "doors": [],
  "chests": [],
  "objectives": [],
  "minibosses": [],
  "waystones": [
    {
      "id": "hearth_stone",
      "x": 7,
      "y": 12
    }
  ],
  "plates": [],
  "ambushes": []
} as const satisfies CompiledMap;
