// GENERATED by npm run genmaps from content/maps/hoarfrost.map.txt - DO NOT EDIT
import type { CompiledMap } from '../../core/mapdefs.ts';

export const hoarfrost = {
  "id": "hoarfrost",
  "width": 30,
  "height": 20,
  "music": "northhollow",
  "tiles": [
    "ooo-oooooooooooooooooooooooooo",
    "o............................o",
    "o............................o",
    "o............................o",
    "o............................o",
    "o............................o",
    "o...........,,,,,,,,,,,,,,...o",
    "o...........,,,,,,,,,,,,,,...o",
    "o...........,,,,,,,,,,,,,,...o",
    "o...........,,,,,,,,,,,,,,...o",
    "o...........,,,,,,,,,,,,,,...o",
    "o............................o",
    "o............................o",
    "o..,,,,,,,,..................o",
    "o..,,,,,,,,..................o",
    "o..,,,,,,,,..................o",
    "o..,,,,,,,,..................o",
    "o..,,,,,,,,..................o",
    "o............................o",
    "oooooooooooooooooooooooooooooo"
  ],
  "spawn": {
    "x": 3,
    "y": 2,
    "facing": "down"
  },
  "zones": [
    {
      "name": "fields",
      "rect": {
        "x1": 12,
        "y1": 6,
        "x2": 25,
        "y2": 10
      },
      "table": "hoarfrost.fields"
    },
    {
      "name": "deep",
      "rect": {
        "x1": 3,
        "y1": 13,
        "x2": 10,
        "y2": 17
      },
      "table": "hoarfrost.deep"
    }
  ],
  "exits": [
    {
      "x": 3,
      "y": 0,
      "to": "wayhold",
      "tx": 18,
      "ty": 6
    }
  ],
  "npcs": [
    {
      "id": "armorer",
      "x": 5,
      "y": 3,
      "dialogue": "armorer_base"
    }
  ],
  "signs": [
    {
      "x": 6,
      "y": 2,
      "dialogue": "hoarfrost_sign"
    }
  ],
  "lore": [
    {
      "x": 26,
      "y": 3,
      "dialogue": "lore_hoarfrost"
    }
  ],
  "springs": [],
  "shrines": [],
  "egates": [],
  "bosses": [
    {
      "id": "rimehound",
      "x": 24,
      "y": 11
    },
    {
      "id": "hoarwarden",
      "x": 24,
      "y": 18
    }
  ],
  "gates": [],
  "triggers": [],
  "trials": [],
  "theme": "frost",
  "portals": [],
  "levers": [],
  "doors": [],
  "chests": [],
  "objectives": [],
  "minibosses": [],
  "waystones": [
    {
      "id": "hoar_stone",
      "x": 3,
      "y": 4
    }
  ],
  "plates": [],
  "ambushes": []
} as const satisfies CompiledMap;
