// GENERATED by npm run genmaps - DO NOT EDIT
import type { CompiledMap } from '../../core/mapdefs.ts';
import type { MapId } from '../../core/state.ts';
import { ashenreach } from './ashenreach.ts';
import { hearth } from './hearth.ts';
import { hearthvale } from './hearthvale.ts';
import { northhollow } from './northhollow.ts';
import { sanctum } from './sanctum.ts';
import { sunkencrypt } from './sunkencrypt.ts';
import { westwood } from './westwood.ts';

export const MAPS: Partial<Record<MapId, CompiledMap>> = {
  ashenreach,
  hearth,
  hearthvale,
  northhollow,
  sanctum,
  sunkencrypt,
  westwood,
};
