// GENERATED by npm run genmaps - DO NOT EDIT
import type { CompiledMap } from '../../core/mapdefs.ts';
import type { MapId } from '../../core/state.ts';
import { ashenreach } from './ashenreach.ts';
import { cinderwaste } from './cinderwaste.ts';
import { circuitvault } from './circuitvault.ts';
import { hearth } from './hearth.ts';
import { hearthvale } from './hearthvale.ts';
import { hoarfrost } from './hoarfrost.ts';
import { northhollow } from './northhollow.ts';
import { sanctum } from './sanctum.ts';
import { stormreach } from './stormreach.ts';
import { sunkencrypt } from './sunkencrypt.ts';
import { wayhold } from './wayhold.ts';
import { westwood } from './westwood.ts';

export const MAPS: Partial<Record<MapId, CompiledMap>> = {
  ashenreach,
  cinderwaste,
  circuitvault,
  hearth,
  hearthvale,
  hoarfrost,
  northhollow,
  sanctum,
  stormreach,
  sunkencrypt,
  wayhold,
  westwood,
};
