// GENERATED by npm run genmaps from content/maps/sanctum.map.txt - DO NOT EDIT
import type { CompiledMap } from '../../core/mapdefs.ts';

export const sanctum = {
  "id": "sanctum",
  "width": 40,
  "height": 28,
  "music": "sanctum",
  "tiles": [
    "oooooooooooooooooooooooooooooooooooooooo",
    "ooooooooooooooooo......ooooooooooooooooo",
    "ooooooooooooooooo......ooooooooooooooooo",
    "ooooooooooooooooo......ooooooooooooooooo",
    "ooooooooooooooooooo..ooooooooooooooooooo",
    "ooooooooooooooooooo..ooooooooooooooooooo",
    "ooooooooooooooooooo..ooooooooooooooooooo",
    "oo........,,,,,,........,,,,,,........oo",
    "oo........,,,,,,........,,,,,,........oo",
    "oo........ooooooooo..ooooooooo........oo",
    "oo........ooooooooo..ooooooooo........oo",
    "oo........ooooooooo..ooooooooo........oo",
    "oo,,,,....ooooooooo..ooooooooo....,,,,oo",
    "oo,,,,....ooooo..........ooooo....,,,,oo",
    "oo........ooooo..........ooooo........oo",
    "oooooo..ooooooo..........ooooooo..oooooo",
    "oo......,,,,,,............,,,,,,......oo",
    "oo......,,,,,,............,,,,,,......oo",
    "oooo..ooooooooooooo..ooooooooooooo..oooo",
    "oooo..ooooooooooooo..ooooooooooooo..oooo",
    "oooo..ooooooooooooo..ooooooooooooo..oooo",
    "oooo..ooooooooooooo..ooooooooooooo..oooo",
    "oooo..ooooooooooooo..ooooooooooooo..oooo",
    "oooo..ooooooooooooo..ooooooooooooo..oooo",
    "oo....................................oo",
    "oo....................................oo",
    "ooooooooooooooooooo..ooooooooooooooooooo",
    "oooooooooooooooooooooooooooooooooooooooo"
  ],
  "spawn": {
    "x": 20,
    "y": 25,
    "facing": "up"
  },
  "zones": [
    {
      "name": "halls",
      "rect": {
        "x1": 1,
        "y1": 5,
        "x2": 38,
        "y2": 22
      },
      "table": "sanctum.halls"
    }
  ],
  "exits": [
    {
      "x": 20,
      "y": 26,
      "to": "northhollow",
      "tx": 28,
      "ty": 3
    }
  ],
  "npcs": [],
  "signs": [],
  "lore": [
    {
      "x": 3,
      "y": 24,
      "dialogue": "lore_sanctum_1"
    },
    {
      "x": 35,
      "y": 21,
      "dialogue": "lore_sanctum_2"
    },
    {
      "x": 19,
      "y": 6,
      "dialogue": "lore_sanctum_3"
    }
  ],
  "springs": [
    {
      "x": 4,
      "y": 21
    }
  ],
  "shrines": [],
  "egates": [],
  "bosses": [
    {
      "id": "hollowwarden",
      "x": 20,
      "y": 2
    }
  ],
  "gates": [],
  "triggers": [],
  "trials": [
    {
      "key": "shatter",
      "x": 4,
      "y": 10
    },
    {
      "key": "blight",
      "x": 35,
      "y": 10
    },
    {
      "key": "kindle",
      "x": 20,
      "y": 14
    }
  ]
} as const satisfies CompiledMap;
