// GENERATED by npm run genmaps from content/maps/sunkencrypt.map.txt - DO NOT EDIT
import type { CompiledMap } from '../../core/mapdefs.ts';

export const sunkencrypt = {
  "id": "sunkencrypt",
  "width": 17,
  "height": 13,
  "music": "sanctum",
  "tiles": [
    "ooooooooooooooooo",
    "ooooooo---ooooooo",
    "ooooooo---ooooooo",
    "ooooooo---ooooooo",
    "oooooooo-oooooooo",
    "oooooooo-oooooooo",
    "oooooooo-oooooooo",
    "o---------------o",
    "o----,,,,,,-----o",
    "o---------------o",
    "o---------------o",
    "o---------------o",
    "ooooooooooooooooo"
  ],
  "spawn": {
    "x": 12,
    "y": 11,
    "facing": "up"
  },
  "zones": [
    {
      "name": "flooded",
      "rect": {
        "x1": 1,
        "y1": 7,
        "x2": 15,
        "y2": 9
      },
      "table": "sunkencrypt.flooded"
    }
  ],
  "exits": [],
  "npcs": [],
  "signs": [
    {
      "x": 2,
      "y": 7,
      "dialogue": "crypt_order"
    }
  ],
  "lore": [
    {
      "x": 14,
      "y": 8,
      "dialogue": "lore_crypt"
    }
  ],
  "springs": [],
  "shrines": [],
  "egates": [],
  "bosses": [],
  "gates": [],
  "triggers": [],
  "trials": [],
  "theme": "cave",
  "portals": [
    {
      "dungeon": "sunkencrypt",
      "x": 3,
      "y": 11,
      "to": "hearthvale",
      "tx": 6,
      "ty": 20
    }
  ],
  "levers": [
    {
      "id": "sluice_a",
      "x": 4,
      "y": 9
    },
    {
      "id": "sluice_b",
      "x": 12,
      "y": 9
    },
    {
      "id": "sluice_c",
      "x": 7,
      "y": 10
    }
  ],
  "doors": [
    {
      "id": "sluice_gate",
      "x": 8,
      "y": 5,
      "needs": "seq:sluice_a,sluice_b,sluice_c"
    }
  ],
  "chests": [],
  "objectives": [
    {
      "id": "crypt_boss",
      "x": 8,
      "y": 2,
      "battle": "crypt_guardians"
    }
  ],
  "minibosses": [
    {
      "id": "crypt_sentry",
      "x": 3,
      "y": 9,
      "species": "boneshade",
      "lv": 7
    }
  ],
  "waystones": [],
  "plates": [],
  "ambushes": [
    {
      "id": "nave_guard",
      "x": 8,
      "y": 6,
      "table": "sunkencrypt.flooded",
      "lv": 6,
      "repeat": false
    }
  ]
} as const satisfies CompiledMap;
