// GENERATED by npm run genmaps from content/maps/wayhold.map.txt - DO NOT EDIT
import type { CompiledMap } from '../../core/mapdefs.ts';

export const wayhold = {
  "id": "wayhold",
  "width": 20,
  "height": 14,
  "music": "hearth",
  "tiles": [
    "oooooooooo-ooooooooo",
    "o..................o",
    "o..................o",
    "o..................o",
    "o..................o",
    "o..................o",
    "-..................-",
    "o..................o",
    "o..................o",
    "o..................o",
    "o..................o",
    "o..................o",
    "o..................o",
    "oooooooooo-ooooooooo"
  ],
  "spawn": {
    "x": 10,
    "y": 11,
    "facing": "up"
  },
  "zones": [],
  "exits": [
    {
      "x": 10,
      "y": 13,
      "to": "hearth",
      "tx": 22,
      "ty": 18
    },
    {
      "x": 0,
      "y": 6,
      "to": "cinderwaste",
      "tx": 3,
      "ty": 1
    },
    {
      "x": 19,
      "y": 6,
      "to": "hoarfrost",
      "tx": 3,
      "ty": 1
    },
    {
      "x": 10,
      "y": 0,
      "to": "stormreach",
      "tx": 3,
      "ty": 1
    }
  ],
  "npcs": [
    {
      "id": "armorer",
      "x": 6,
      "y": 5,
      "dialogue": "armorer_base"
    },
    {
      "id": "wayfarer",
      "x": 13,
      "y": 5,
      "dialogue": "wayhold_roads"
    }
  ],
  "signs": [
    {
      "x": 4,
      "y": 9,
      "dialogue": "wayhold_sign"
    }
  ],
  "lore": [
    {
      "x": 15,
      "y": 9,
      "dialogue": "lore_wayhold"
    }
  ],
  "springs": [],
  "shrines": [],
  "egates": [],
  "bosses": [],
  "gates": [],
  "triggers": [],
  "trials": [],
  "theme": "vale",
  "portals": [],
  "levers": [],
  "doors": [],
  "chests": [],
  "objectives": [],
  "minibosses": [],
  "waystones": [
    {
      "id": "wayhold_stone",
      "x": 10,
      "y": 7
    }
  ],
  "plates": [],
  "ambushes": []
} as const satisfies CompiledMap;
